### PR TITLE
Updated 2.1.preview-0 schema based on TJ's feedback and renamed it to…

### LINKED ISSUE #5794: Update Skill Manifest 2.1.preview-0 to work with Composer editing experience
## Issue
We're currently adding a skill manifest editor to Composer, and in order to make the schema work with the AdaptiveForm editor, we had to make several small changes to the schema. 

## Proposed change
Here are the changes to each property in the schema we would like to see changed

- Tags
  - Define the items' type as string
  - ```diff
    "tags": {
      "type": "array",
      "uniqueItems": true,
    - "description": "An array of strings with tags for the skill"
    + "description": "An array of strings with tags for the skill",
    + "items": {
    +   "type": "string"
    + }
    },
    ```
- Dispatch Models
  - Languages/Intent
    - Remove `oneOf` attribute since there is only one item in the array
    - ```diff
      "languages": {
        "type": "object",
        "description": "List of languages supported by the skill",
        "minProperties": 1,
        "additionalProperties": {
      -   "oneOf": [
      -     {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "description": "List of language models supported by the skill",
              "items": {
                  "$ref": "#/definitions/languageModel"
              }                               
      -     } 
      -   ]
        }
      }
      ```
- Activities/Activities sent 
  - Changed `anyOf` in `additionalProperties` to `oneOf`
  - ```diff
    "activities": {
      "type": "object",
      "description": "Definition for the activities accepted by the skill",
      "additionalProperties": {
    -   "anyOf": [
    +   "oneOf": [

                {
                    "$ref": "#/definitions/eventActivity"
                },
                {
                    "$ref": "#/definitions/invokeActivity"
                },
                {
                    "$ref": "#/definitions/messageActivity"
                }
            ]
        }
    },
    ```
- Event/Invoke/Message Activities
  - Changed type from an enum with one option to use a const value
  - Added titles for drop-down selection
  - ```diff
    "eventActivity": {
    + "title": "Event Activity",
      "type": "object",
      "description": "An activity with Type=Event where the Name property indicates the task that the skill will execute",
      "required": [
          "type",
          "name"
      ],
      "properties": {
          "type": {
              "type": "string",
              "description": "The activity type",
    -         "enum": [
    -           "event"
    -         ]
    +         "const": "event"
          },
        ...
      }
    }
    ```
## Component Impact 
Skills Manifest

## Customer Impact 
MicrosoftTeams-image (1)

### PR DESCRIPTION
**Pull request by gabog**
Fixes #5794 

- Updated 2.1.preview-0 schema based on TJ's feedback and renamed it to 2.1.preview-1.
- Removed ID property from languageModel.
- Changed Intents to be just an array of strings.
- Updated sample schemas to use string types instead of time and date (that are not supported in json schema).

### CODE REVIEW

**Comment by gabog** [comment]
@tomlm, @tdurnford & @cwhitten, are you guys OK with these changes? Can you please review/approve/comment on this PR?

Thanks

**Comment by tomlm** [comment]
>                 ]

This should NOT Be a restriction.  Any Activity should be valid. 
This should be replaced with
```
"$ref":"[https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/protocol/botframework.json#/definitions/Activity](https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/protocol/botframework.json#/definitions/Activity)",
"required": [ "type" ]
```

---
Refers to: schemas/skills/skill-manifest-2.1.preview-1.json:119 in aced62c. [](commit_id = aced62cbf1f062734b2da53cefee05de9b485f55, deletion_comment = False)

**Comment by tomlm** [comment]
>                 ]

This should NOT Be a restriction.  Any Activity should be valid. 
This should be replaced with
```
"$ref":"[[https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/protocol/botframework.json#/definitions/Activity](https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/protocol/botframework.json#/definitions/Activity)](https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/protocol/botframework.json#/definitions/Activity)",
"required": [ "type" ]
```

---
Refers to: schemas/skills/skill-manifest-2.1.preview-1.json:119 in aced62c. [](commit_id = aced62cbf1f062734b2da53cefee05de9b485f55, deletion_comment = False)

**Comment by tomlm** [comment]
>                 ]

This should NOT Be a restriction.  Any Activity should be valid. 
This should be replaced with
```
"$ref":"[[https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/protocol/botframework.json#/definitions/Activity](https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/protocol/botframework.json#/definitions/Activity)](https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/protocol/botframework.json#/definitions/Activity)",
"required": [ "type" ]
```

---
Refers to: schemas/skills/skill-manifest-2.1.preview-1.json:136 in aced62c. [](commit_id = aced62cbf1f062734b2da53cefee05de9b485f55, deletion_comment = False)

**Comment by tomlm** [comment]
>         },

These should be removed.

---
Refers to: schemas/skills/skill-manifest-2.1.preview-1.json:300 in aced62c. [](commit_id = aced62cbf1f062734b2da53cefee05de9b485f55, deletion_comment = False)

**Comment by tdurnford** [comment]
How is the `resultValue` property represented in the activity if we are using https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/protocol/botframework.json#/definitions/Activity instead of defining it in the schema? It doesn't look like the `Activity` definition has `resultValue`.

**Pull request merged**
